apiVersion: v1
kind: ConfigMap
metadata:
  name: archburgers-db-access-config
data:
  "archburgers.datasource.driverClass": "org.postgresql.Driver"
  "archburgers.datasource.db_name": "archburgers"
  "archburgers.datasource.dbUrl": "jdbc:postgresql://__DB_URL__/postgres?autoReconnect=true"
  "archburgers.datasource.dbUser": "burger"
  # TODO before production - move password to a Secret
  "archburgers.datasource.dbPass": "Burgers2024"

