name: Terraform plan
run-name: Terraform plan
on: push   # TODO: Em teste! Mudar condição para apenas na branch main! (PR aceito)

jobs:
  terraform-apply:
    uses: ./.github/workflows/_run-terraform-command.yml
    with:
      TERRAFORM_COMMAND: apply --auto-approve

      AWS_REGION: us-east-1
      TF_STATE_BUCKET_NAME: ${{vars.TF_STATE_BUCKET_NAME}}
      TF_STATE_BUCKET_PATH: ${{vars.TF_STATE_BUCKET_PATH}}
      TF_LOCK_TABLE_NAME: ${{vars.TF_LOCK_TABLE_NAME}}
    secrets: inherit

  kubernetes-deploy:
    runs-on: ubuntu-latest
    needs: terraform-apply
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: TODO
        run: echo "EM CONSTRUÇÃO"
