name: Terraform plan
run-name: Terraform plan
on: push   # TODO: Especificar apenas apos PR aberto

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    needs: aws-and-terraform-setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Create S3 Bucket
        run: ./utils/create-s3-bucket.sh ${{ vars.TF_STATE_BUCKET_NAME }}

      - name: Create Dynamodb table
        run: ./utils/create-dyndb-table.sh ${{ vars.TF_LOCK_TABLE_NAME }}

      - name: Terraform Init
        run: |
          cd terraform && terraform init \
            -backend-config="bucket=${{ vars.TF_STATE_BUCKET_NAME }}" \
            -backend-config="key=${{ vars.TF_STATE_BUCKET_PATH }}" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=${{ vars.TF_LOCK_TABLE_NAME }}"

      - name: Terraform plan
        working-directory: ./terraform
        run: terraform plan
